title: HackGT
email: hello@hack.gt
description: > # this means to ignore newlines until "baseurl:"
  HackGT Organization Website

baseurl: ""
url: "hack.gt"
twitter_username: TheHackGT
github_username:  HackGT

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed

include: ['_pages']

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .bundle
  - vendor
  - Dockerfile
  - .dockerignore
  - .gitignore
  - docker_resources
  - deployment.yaml
  - precheck.rb
  - LICENSE

# collections_dir: content

collections:
  - homepage
  - events
  - privacy
  - upcoming_events
  - event_blurbs
  - members
  - frontpage_blurbs
  - teams
  - projects
  - highlights
  - posts