FROM debian:8

WORKDIR /src
ADD . /src

RUN apt-get update && apt-get install -y \
    build-essential \
    imagemagick \
    libmagickwand-dev \
    curl
RUN curl -L https://get.rvm.io | bash -s stable
RUN /bin/bash -l -c "rvm install 2.4.1"
RUN ls

RUN /bin/bash -l -c "gem install bundler && bundle install --path vendor/bundle"
CMD ["/bin/bash", "-l", "-c", "bundle", "exec", "jekyll", "build"]

